# Generated by Django 3.1.1 on 2020-12-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page',
            name='images',
            field=models.ImageField(null=True, upload_to='media/photos'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='heading',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='showcase',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
