# Generated by Django 3.1.1 on 2020-12-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201207_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showcase',
            old_name='showcase',
            new_name='body',
        ),
    ]
