# Generated by Django 3.1.1 on 2020-12-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20201207_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
