# Generated by Django 3.1.1 on 2020-12-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201207_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('about_me', models.TextField(null=True)),
                ('title', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/about_me')),
                ('top_text', models.TextField(max_length=300, null=True)),
            ],
        ),
    ]
