# Generated by Django 3.1.1 on 2020-12-07 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
