# Generated by Django 3.1.1 on 2020-12-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_home_page_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home_page',
            options={'ordering': ['date_posted']},
        ),
    ]
