# Generated by Django 3.1.1 on 2020-12-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20201207_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home_page',
            options={'ordering': ['-date_posted']},
        ),
    ]
