# Generated by Django 3.1.1 on 2020-12-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20201207_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
