# Generated by Django 3.1.1 on 2020-12-08 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20201207_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 6, 16, 37, 66981)),
        ),
    ]
